services:
  - type: web
    name: jaagee-lab
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    region: oregon
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lims_project.settings.base
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: jaagee-lab.onrender.com
      - key: DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        value: your_api_key_here
    ports:
      - port: 8000
        protocol: http
